# Generated by Django 3.0.7 on 2023-04-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(default='Ram', max_length=100),
        ),
    ]
